### ISSUE TITLE
Project to upload: Coire

### ISSUE THREAD

**Issue by mandiewilliams** [nycda/student-projects#16]
@Johnwolfe 

title: Current Radio
Student: Coire Walker
course: Web Development Intensive (link http://nycda.com/classes/web-development-intensive/)
![screen shot 2015-07-24 at 4 52 48 pm](https://cloud.githubusercontent.com/assets/8107766/8884440/a22241ee-3224-11e5-8821-da9f335c622a.png)

url: http://currentradio.net/

more to come!

**Comment by Johnwolfe** [comment]
Should be up with current PR
