### ISSUE TITLE
upload Dmitrii's project to porjects page

### ISSUE THREAD

**Issue by mandiewilliams** [nycda/student-projects#21]
Name: Dmitrii Sim
Project title: Portfolio
link: http://www.dmitriisim.com/
Course: Front End 101

**Comment by mandiewilliams** [comment]
![dmitrii](https://cloud.githubusercontent.com/assets/8107766/9124206/058f5a62-3c63-11e5-9332-11eeb89ea901.jpg)

**Comment by Johnwolfe** [comment]
Done! closing
