### ISSUE TITLE
dan barrett's project to upload

### ISSUE THREAD

**Issue by mandiewilliams** [nycda/student-projects#23]
Name: Dan Barrett
Project: S_nth

http://dmbarrett.github.io/s_nth/

Course: Web Development Intensive

http://nycda.com/classes/web-development-intensive/
<img width="1026" alt="screen shot 2015-08-21 at 3 10 52 pm" src="https://cloud.githubusercontent.com/assets/8107766/9417003/e5d41d42-4816-11e5-89a3-504ceb930201.png">

**Comment by Johnwolfe** [comment]
Should be done with latest pull-request

**Comment by zachfeldman** [comment]
Done!
